module BlueHive
  module Models
    type health_check_params =
      {  } & BlueHive::Internal::Type::request_parameters

    class HealthCheckParams < BlueHive::Internal::Type::BaseModel
      extend BlueHive::Internal::Type::RequestParameters::Converter
      include BlueHive::Internal::Type::RequestParameters

      def initialize: (?request_options: BlueHive::request_opts) -> void

      def to_hash: -> { request_options: BlueHive::RequestOptions }
    end
  end
end
