module BlueHive
  module Resources
    class Providers
      def lookup: (
        ?firstname: String,
        ?lastname: String,
        ?npi: String,
        ?zipcode: String,
        ?request_options: BlueHive::request_opts
      ) -> BlueHive::Models::ProviderLookupResponse

      def initialize: (client: BlueHive::Client) -> void
    end
  end
end
